"""add selections

Revision ID: 3839b6b0713d
Revises: 84952fa87d76
Create Date: 2024-05-31 08:50:12.327467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3839b6b0713d'
down_revision = '84952fa87d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_pieces')
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('fk_pieces_order_id_orders', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pieces_order_id_orders', 'orders', ['order_id'], ['id'])
        batch_op.drop_column('sold')

    op.create_table('_alembic_tmp_pieces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sold', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
