"""add payment intent column to orders

Revision ID: 84952fa87d76
Revises: 8e5c4e401a11
Create Date: 2024-05-31 08:24:14.157807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84952fa87d76'
down_revision = '8e5c4e401a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_intent')

    # ### end Alembic commands ###
