"""add pieces foreign key order

Revision ID: 8e5c4e401a11
Revises: ce6d29eaa601
Create Date: 2024-05-30 20:06:56.248834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5c4e401a11'
down_revision = 'ce6d29eaa601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pieces_order_id_orders'), 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pieces_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
