"""add sels

Revision ID: b49bde7bace5
Revises: 3839b6b0713d
Create Date: 2024-05-31 09:18:38.420596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49bde7bace5'
down_revision = '3839b6b0713d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_selections_order_id_orders')),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_selections_piece_id_pieces')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('fk_pieces_order_id_orders', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pieces_order_id_orders', 'orders', ['order_id'], ['id'])
        batch_op.drop_column('sold')

    op.drop_table('selections')
    # ### end Alembic commands ###
